version: '3.8'
services:
  terra-bot:
    build: .
    image: terra-bot:latest
    #platform: linux/arm64
    devices:
      - "/dev/bus/usb:/dev/bus/usb"  # Grant access to USB for RealSense
      - "/dev/spidev0.0:/dev/spidev0.0"  # Access to SPI for CAN HAT (adjust if necessary)
      - "/dev/spidev0.1:/dev/spidev0.1"  # Additional SPI access if required
      - "/dev/can0:/dev/can0"  # Access to CAN interface
    volumes:
      - /dev:/dev  # Broad device access, refine if necessary for security
      #- ./ros_ws:/ros_ws
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'    
    network_mode: host
    privileged: true
    environment:
      - UDEV=1
    restart: unless-stopped
    tty: true

